// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
export { Ad as Andorra } from './Ad';
export { Ad } from './Ad';
export { Ae as UnitedArabEmirates } from './Ae';
export { Ae } from './Ae';
export { Af as Afghanistan } from './Af';
export { Af } from './Af';
export { Ag as AntiguaAndBarbuda } from './Ag';
export { Ag } from './Ag';
export { Ai as Anguilla } from './Ai';
export { Ai } from './Ai';
export { Al as Albania } from './Al';
export { Al } from './Al';
export { Am as Armenia } from './Am';
export { Am } from './Am';
export { Ao as Angola } from './Ao';
export { Ao } from './Ao';
export { Ar as Argentina } from './Ar';
export { Ar } from './Ar';
export { As as AmericanSamoa } from './As';
export { As } from './As';
export { At as Austria } from './At';
export { At } from './At';
export { Au as Australia } from './Au';
export { Au } from './Au';
export { AuMainland } from './AuMainland';
export { Aw as Aruba } from './Aw';
export { Aw } from './Aw';
export { Az as Azerbaijan } from './Az';
export { Az } from './Az';
export { AzMainland } from './AzMainland';
export { Ba as BosniaAndHerzegovina } from './Ba';
export { Ba } from './Ba';
export { Bb as Barbados } from './Bb';
export { Bb } from './Bb';
export { Bd as Bangladesh } from './Bd';
export { Bd } from './Bd';
export { Be as Belgium } from './Be';
export { Be } from './Be';
export { Bf as BurkinaFaso } from './Bf';
export { Bf } from './Bf';
export { Bg as Bulgaria } from './Bg';
export { Bg } from './Bg';
export { Bh as Bahrain } from './Bh';
export { Bh } from './Bh';
export { BhMainland } from './BhMainland';
export { Bi as Burundi } from './Bi';
export { Bi } from './Bi';
export { Bj as Benin } from './Bj';
export { Bj } from './Bj';
export { Bl as SaintBarthelemy } from './Bl';
export { Bl } from './Bl';
export { Bm as Bermuda } from './Bm';
export { Bm } from './Bm';
export { Bn as Brunei } from './Bn';
export { Bn } from './Bn';
export { Bo as Bolivia } from './Bo';
export { Bo } from './Bo';
export { BqBonaire as Bonaire } from './BqBonaire';
export { BqBonaire } from './BqBonaire';
export { BqSintEustatius as SintEustatius } from './BqSintEustatius';
export { BqSintEustatius } from './BqSintEustatius';
export { Br as Brazil } from './Br';
export { Br } from './Br';
export { Bs as Bahamas } from './Bs';
export { Bs } from './Bs';
export { BsAndros } from './BsAndros';
export { Bt as Bhutan } from './Bt';
export { Bt } from './Bt';
export { Bv as BouvetIsland } from './Bv';
export { Bv } from './Bv';
export { Bw as Botswana } from './Bw';
export { Bw } from './Bw';
export { By as Belarus } from './By';
export { By } from './By';
export { Bz as Belize } from './Bz';
export { Bz } from './Bz';
export { Ca as Canada } from './Ca';
export { Ca } from './Ca';
export { Cc as CocosKeelingIslands } from './Cc';
export { Cc } from './Cc';
export { Cd as DrCongo } from './Cd';
export { Cd } from './Cd';
export { Cf as CentralAfricanRepublic } from './Cf';
export { Cf } from './Cf';
export { Cg as RepublicOfTheCongo } from './Cg';
export { Cg } from './Cg';
export { Ch as Switzerland } from './Ch';
export { Ch } from './Ch';
export { Ci as CoteDIvoire } from './Ci';
export { Ci } from './Ci';
export { Ck as CookIslands } from './Ck';
export { Ck } from './Ck';
export { Cl as Chile } from './Cl';
export { Cl } from './Cl';
export { Cm as Cameroon } from './Cm';
export { Cm } from './Cm';
export { Cn as China } from './Cn';
export { Cn } from './Cn';
export { Co as Colombia } from './Co';
export { Co } from './Co';
export { Cr as CostaRica } from './Cr';
export { Cr } from './Cr';
export { Cu as Cuba } from './Cu';
export { Cu } from './Cu';
export { Cv as CapeVerde } from './Cv';
export { Cv } from './Cv';
export { Cw as Curacao } from './Cw';
export { Cw } from './Cw';
export { Cx as ChristmasIsland } from './Cx';
export { Cx } from './Cx';
export { Cy as Cyprus } from './Cy';
export { Cy } from './Cy';
export { Cz as Czechia } from './Cz';
export { Cz } from './Cz';
export { De as Germany } from './De';
export { De } from './De';
export { Dj as Djibouti } from './Dj';
export { Dj } from './Dj';
export { Dk as Denmark } from './Dk';
export { Dk } from './Dk';
export { Dm as Dominica } from './Dm';
export { Dm } from './Dm';
export { Do as DominicanRepublic } from './Do';
export { Do } from './Do';
export { Dz as Algeria } from './Dz';
export { Dz } from './Dz';
export { Ec as Ecuador } from './Ec';
export { Ec } from './Ec';
export { Ee as Estonia } from './Ee';
export { Ee } from './Ee';
export { Eg as Egypt } from './Eg';
export { Eg } from './Eg';
export { Eh as WesternSahara } from './Eh';
export { Eh } from './Eh';
export { England } from './England';
export { Er as Eritrea } from './Er';
export { Er } from './Er';
export { Es as Spain } from './Es';
export { Es } from './Es';
export { Et as Ethiopia } from './Et';
export { Et } from './Et';
export { Fi as Finland } from './Fi';
export { Fi } from './Fi';
export { Fj as Fiji } from './Fj';
export { Fj } from './Fj';
export { Fk as FalklandIslandsMalvinas } from './Fk';
export { Fk } from './Fk';
export { Fm as Micronesia } from './Fm';
export { Fm } from './Fm';
export { Fo as FaroeIslands } from './Fo';
export { Fo } from './Fo';
export { Fr as France } from './Fr';
export { Fr } from './Fr';
export { FrMainland } from './FrMainland';
export { Ga as Gabon } from './Ga';
export { Ga } from './Ga';
export { Gd as Grenada } from './Gd';
export { Gd } from './Gd';
export { Ge as Georgia } from './Ge';
export { Ge } from './Ge';
export { Gf as FrenchGuiana } from './Gf';
export { Gf } from './Gf';
export { Gg as Guernsey } from './Gg';
export { Gg } from './Gg';
export { Gh as Ghana } from './Gh';
export { Gh } from './Gh';
export { Gi as Gibraltar } from './Gi';
export { Gi } from './Gi';
export { Gl as Greenland } from './Gl';
export { Gl } from './Gl';
export { Gm as Gambia } from './Gm';
export { Gm } from './Gm';
export { Gn as Guinea } from './Gn';
export { Gn } from './Gn';
export { Gp as Guadeloupe } from './Gp';
export { Gp } from './Gp';
export { Gq as EquatorialGuinea } from './Gq';
export { Gq } from './Gq';
export { Gr as Greece } from './Gr';
export { Gr } from './Gr';
export { Gs as SouthGeorgiaAndTheSouthSandwichIslands } from './Gs';
export { Gs } from './Gs';
export { Gt as Guatemala } from './Gt';
export { Gt } from './Gt';
export { Gu as Guam } from './Gu';
export { Gu } from './Gu';
export { Gw as GuineaBissau } from './Gw';
export { Gw } from './Gw';
export { Gy as Guyana } from './Gy';
export { Gy } from './Gy';
export { Hk as HongKong } from './Hk';
export { Hk } from './Hk';
export { Hm as HeardIslandAndMcdonaldIslands } from './Hm';
export { Hm } from './Hm';
export { Hn as Honduras } from './Hn';
export { Hn } from './Hn';
export { Hr as Croatia } from './Hr';
export { Hr } from './Hr';
export { Ht as Haiti } from './Ht';
export { Ht } from './Ht';
export { Hu as Hungary } from './Hu';
export { Hu } from './Hu';
export { Id as Indonesia } from './Id';
export { Id } from './Id';
export { Ie as Ireland } from './Ie';
export { Ie } from './Ie';
export { Il as Israel } from './Il';
export { Il } from './Il';
export { Im as IsleOfMan } from './Im';
export { Im } from './Im';
export { In as India } from './In';
export { In } from './In';
export { Iq as Iraq } from './Iq';
export { Iq } from './Iq';
export { Ir as Iran } from './Ir';
export { Ir } from './Ir';
export { Is as Iceland } from './Is';
export { Is } from './Is';
export { It as Italy } from './It';
export { It } from './It';
export { Je as Jersey } from './Je';
export { Je } from './Je';
export { Jm as Jamaica } from './Jm';
export { Jm } from './Jm';
export { Jo as Jordan } from './Jo';
export { Jo } from './Jo';
export { Jp as Japan } from './Jp';
export { Jp } from './Jp';
export { Ke as Kenya } from './Ke';
export { Ke } from './Ke';
export { Kg as Kyrgyzstan } from './Kg';
export { Kg } from './Kg';
export { Kh as Cambodia } from './Kh';
export { Kh } from './Kh';
export { Ki as Kiribati } from './Ki';
export { Ki } from './Ki';
export { Km as Comoros } from './Km';
export { Km } from './Km';
export { Kn as SaintKittsAndNevis } from './Kn';
export { Kn } from './Kn';
export { Kp as NorthKorea } from './Kp';
export { Kp } from './Kp';
export { Kr as SouthKorea } from './Kr';
export { Kr } from './Kr';
export { Kw as Kuwait } from './Kw';
export { Kw } from './Kw';
export { Ky as CaymanIslands } from './Ky';
export { Ky } from './Ky';
export { Kz as Kazakhstan } from './Kz';
export { Kz } from './Kz';
export { La as Laos } from './La';
export { La } from './La';
export { Lb as Lebanon } from './Lb';
export { Lb } from './Lb';
export { Lc as SaintLucia } from './Lc';
export { Lc } from './Lc';
export { Li as Liechtenstein } from './Li';
export { Li } from './Li';
export { Lk as SriLanka } from './Lk';
export { Lk } from './Lk';
export { Lr as Liberia } from './Lr';
export { Lr } from './Lr';
export { Ls as Lesotho } from './Ls';
export { Ls } from './Ls';
export { Lt as Lithuania } from './Lt';
export { Lt } from './Lt';
export { Lu as Luxembourg } from './Lu';
export { Lu } from './Lu';
export { Lv as Latvia } from './Lv';
export { Lv } from './Lv';
export { Ly as Libya } from './Ly';
export { Ly } from './Ly';
export { Ma as Morocco } from './Ma';
export { Ma } from './Ma';
export { Mc as Monaco } from './Mc';
export { Mc } from './Mc';
export { Md as Moldova } from './Md';
export { Md } from './Md';
export { Me as Montenegro } from './Me';
export { Me } from './Me';
export { Mf as SaintMartinFrenchPart } from './Mf';
export { Mf } from './Mf';
export { Mg as Madagascar } from './Mg';
export { Mg } from './Mg';
export { Mh as MarshallIslands } from './Mh';
export { Mh } from './Mh';
export { Mk as NorthMacedonia } from './Mk';
export { Mk } from './Mk';
export { Ml as Mali } from './Ml';
export { Ml } from './Ml';
export { Mm as Myanmar } from './Mm';
export { Mm } from './Mm';
export { Mn as Mongolia } from './Mn';
export { Mn } from './Mn';
export { Mo as Macau } from './Mo';
export { Mo } from './Mo';
export { Mp as NorthernMarianaIslands } from './Mp';
export { Mp } from './Mp';
export { Mq as Martinique } from './Mq';
export { Mq } from './Mq';
export { Mr as Mauritania } from './Mr';
export { Mr } from './Mr';
export { Ms as Montserrat } from './Ms';
export { Ms } from './Ms';
export { Mt as Malta } from './Mt';
export { Mt } from './Mt';
export { Mu as Mauritius } from './Mu';
export { Mu } from './Mu';
export { Mv as Maldives } from './Mv';
export { Mv } from './Mv';
export { Mw as Malawi } from './Mw';
export { Mw } from './Mw';
export { Mx as Mexico } from './Mx';
export { Mx } from './Mx';
export { My as Malaysia } from './My';
export { My } from './My';
export { Mz as Mozambique } from './Mz';
export { Mz } from './Mz';
export { Na as Namibia } from './Na';
export { Na } from './Na';
export { Nc as NewCaledonia } from './Nc';
export { Nc } from './Nc';
export { Ne as Niger } from './Ne';
export { Ne } from './Ne';
export { Nf as NorfolkIsland } from './Nf';
export { Nf } from './Nf';
export { Ng as Nigeria } from './Ng';
export { Ng } from './Ng';
export { Ni as Nicaragua } from './Ni';
export { Ni } from './Ni';
export { Nl as Netherlands } from './Nl';
export { Nl } from './Nl';
export { No as Norway } from './No';
export { No } from './No';
export { NorthernIreland } from './NorthernIreland';
export { Np as Nepal } from './Np';
export { Np } from './Np';
export { Nr as Nauru } from './Nr';
export { Nr } from './Nr';
export { Nu as Niue } from './Nu';
export { Nu } from './Nu';
export { Nz as NewZealand } from './Nz';
export { Nz } from './Nz';
export { Om as Oman } from './Om';
export { Om } from './Om';
export { Pa as Panama } from './Pa';
export { Pa } from './Pa';
export { Pe as Peru } from './Pe';
export { Pe } from './Pe';
export { Pf as FrenchPolynesia } from './Pf';
export { Pf } from './Pf';
export { Pg as PapuaNewGuinea } from './Pg';
export { Pg } from './Pg';
export { Ph as Philippines } from './Ph';
export { Ph } from './Ph';
export { Pk as Pakistan } from './Pk';
export { Pk } from './Pk';
export { Pl as Poland } from './Pl';
export { Pl } from './Pl';
export { Pm as SaintPierreAndMiquelon } from './Pm';
export { Pm } from './Pm';
export { Pn as Pitcairn } from './Pn';
export { Pn } from './Pn';
export { Pr as PuertoRico } from './Pr';
export { Pr } from './Pr';
export { Ps as StateOfPalestine } from './Ps';
export { Ps } from './Ps';
export { Pt as Portugal } from './Pt';
export { Pt } from './Pt';
export { Pw as Palau } from './Pw';
export { Pw } from './Pw';
export { Py as Paraguay } from './Py';
export { Py } from './Py';
export { Qa as Qatar } from './Qa';
export { Qa } from './Qa';
export { Re as Reunion } from './Re';
export { Re } from './Re';
export { Ro as Romania } from './Ro';
export { Ro } from './Ro';
export { Rs as Serbia } from './Rs';
export { Rs } from './Rs';
export { Ru as Russia } from './Ru';
export { Ru } from './Ru';
export { Rw as Rwanda } from './Rw';
export { Rw } from './Rw';
export { Sa as SaudiArabia } from './Sa';
export { Sa } from './Sa';
export { Sb as SolomonIslands } from './Sb';
export { Sb } from './Sb';
export { Sc as Seychelles } from './Sc';
export { Sc } from './Sc';
export { Scotland } from './Scotland';
export { Sd as Sudan } from './Sd';
export { Sd } from './Sd';
export { Se as Sweden } from './Se';
export { Se } from './Se';
export { Sg as Singapore } from './Sg';
export { Sg } from './Sg';
export { Sh as SaintHelena } from './Sh';
export { Sh } from './Sh';
export { Si as Slovenia } from './Si';
export { Si } from './Si';
export { Sj as SvalbardAndJanMayen } from './Sj';
export { Sj } from './Sj';
export { Sk as Slovakia } from './Sk';
export { Sk } from './Sk';
export { Sl as SierraLeone } from './Sl';
export { Sl } from './Sl';
export { Sm as SanMarino } from './Sm';
export { Sm } from './Sm';
export { Sn as Senegal } from './Sn';
export { Sn } from './Sn';
export { So as Somalia } from './So';
export { So } from './So';
export { Sr as Suriname } from './Sr';
export { Sr } from './Sr';
export { Ss as SouthSudan } from './Ss';
export { Ss } from './Ss';
export { St as SaoTomeAndPrincipe } from './St';
export { St } from './St';
export { Sv as ElSalvador } from './Sv';
export { Sv } from './Sv';
export { Sx as SintMaartenDutchPart } from './Sx';
export { Sx } from './Sx';
export { Sy as Syria } from './Sy';
export { Sy } from './Sy';
export { Sz as Eswatini } from './Sz';
export { Sz } from './Sz';
export { Tc as TurksAndCaicosIslands } from './Tc';
export { Tc } from './Tc';
export { Td as Chad } from './Td';
export { Td } from './Td';
export { Tf as FrenchSouthernTerritories } from './Tf';
export { Tf } from './Tf';
export { Tg as Togo } from './Tg';
export { Tg } from './Tg';
export { Th as Thailand } from './Th';
export { Th } from './Th';
export { Tj as Tajikistan } from './Tj';
export { Tj } from './Tj';
export { Tk as Tokelau } from './Tk';
export { Tk } from './Tk';
export { Tl as TimorLeste } from './Tl';
export { Tl } from './Tl';
export { Tm as Turkmenistan } from './Tm';
export { Tm } from './Tm';
export { Tn as Tunisia } from './Tn';
export { Tn } from './Tn';
export { To as Tonga } from './To';
export { To } from './To';
export { Tr as Turkiye } from './Tr';
export { Tr } from './Tr';
export { Tt as TrinidadAndTobago } from './Tt';
export { Tt } from './Tt';
export { Tv as Tuvalu } from './Tv';
export { Tv } from './Tv';
export { Tw as Taiwan } from './Tw';
export { Tw } from './Tw';
export { Tz as Tanzania } from './Tz';
export { Tz } from './Tz';
export { Ua as Ukraine } from './Ua';
export { Ua } from './Ua';
export { Ug as Uganda } from './Ug';
export { Ug } from './Ug';
export { Us as UnitedStates } from './Us';
export { Us } from './Us';
export { Uy as Uruguay } from './Uy';
export { Uy } from './Uy';
export { Uz as Uzbekistan } from './Uz';
export { Uz } from './Uz';
export { Va as HolySeeVaticanCityState } from './Va';
export { Va } from './Va';
export { Vc as SaintVincentAndTheGrenadines } from './Vc';
export { Vc } from './Vc';
export { Ve as Venezuela } from './Ve';
export { Ve } from './Ve';
export { Vg as VirginIslandsBritish } from './Vg';
export { Vg } from './Vg';
export { Vi as VirginIslandsUS } from './Vi';
export { Vi } from './Vi';
export { Vn as Vietnam } from './Vn';
export { Vn } from './Vn';
export { Vu as Vanuatu } from './Vu';
export { Vu } from './Vu';
export { Wales } from './Wales';
export { Wf as WallisAndFutuna } from './Wf';
export { Wf } from './Wf';
export { Ws as Samoa } from './Ws';
export { Ws } from './Ws';
export { Xk as Kosovo } from './Xk';
export { Xk } from './Xk';
export { Ye as Yemen } from './Ye';
export { Ye } from './Ye';
export { Yt as Mayotte } from './Yt';
export { Yt } from './Yt';
export { Za as SouthAfrica } from './Za';
export { Za } from './Za';
export { Zm as Zambia } from './Zm';
export { Zm } from './Zm';
export { Zw as Zimbabwe } from './Zw';
export { Zw } from './Zw';
