// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
export { Ad as Andorra } from './Ad.js';
export { Ad } from './Ad.js';
export { Ae as UnitedArabEmirates } from './Ae.js';
export { Ae } from './Ae.js';
export { Af as Afghanistan } from './Af.js';
export { Af } from './Af.js';
export { Ag as AntiguaAndBarbuda } from './Ag.js';
export { Ag } from './Ag.js';
export { Ai as Anguilla } from './Ai.js';
export { Ai } from './Ai.js';
export { Al as Albania } from './Al.js';
export { Al } from './Al.js';
export { Am as Armenia } from './Am.js';
export { Am } from './Am.js';
export { Ao as Angola } from './Ao.js';
export { Ao } from './Ao.js';
export { Ar as Argentina } from './Ar.js';
export { Ar } from './Ar.js';
export { As as AmericanSamoa } from './As.js';
export { As } from './As.js';
export { At as Austria } from './At.js';
export { At } from './At.js';
export { Au as Australia } from './Au.js';
export { Au } from './Au.js';
export { AuMainland as AustraliaMainland } from './AuMainland.js';
export { AuMainland } from './AuMainland.js';
export { Aw as Aruba } from './Aw.js';
export { Aw } from './Aw.js';
export { Az as Azerbaijan } from './Az.js';
export { Az } from './Az.js';
export { AzMainland as AzerbaijanMainland } from './AzMainland.js';
export { AzMainland } from './AzMainland.js';
export { Ba as BosniaAndHerzegovina } from './Ba.js';
export { Ba } from './Ba.js';
export { Bb as Barbados } from './Bb.js';
export { Bb } from './Bb.js';
export { Bd as Bangladesh } from './Bd.js';
export { Bd } from './Bd.js';
export { Be as Belgium } from './Be.js';
export { Be } from './Be.js';
export { Bf as BurkinaFaso } from './Bf.js';
export { Bf } from './Bf.js';
export { Bg as Bulgaria } from './Bg.js';
export { Bg } from './Bg.js';
export { Bh as Bahrain } from './Bh.js';
export { Bh } from './Bh.js';
export { BhMainland as BahrainMainland } from './BhMainland.js';
export { BhMainland } from './BhMainland.js';
export { Bi as Burundi } from './Bi.js';
export { Bi } from './Bi.js';
export { Bj as Benin } from './Bj.js';
export { Bj } from './Bj.js';
export { Bl as SaintBarthelemy } from './Bl.js';
export { Bl } from './Bl.js';
export { Bm as Bermuda } from './Bm.js';
export { Bm } from './Bm.js';
export { Bn as Brunei } from './Bn.js';
export { Bn } from './Bn.js';
export { Bo as Bolivia } from './Bo.js';
export { Bo } from './Bo.js';
export { BqBonaire as Bonaire } from './BqBonaire.js';
export { BqBonaire } from './BqBonaire.js';
export { BqSintEustatius as SintEustatius } from './BqSintEustatius.js';
export { BqSintEustatius } from './BqSintEustatius.js';
export { Br as Brazil } from './Br.js';
export { Br } from './Br.js';
export { Bs as Bahamas } from './Bs.js';
export { Bs } from './Bs.js';
export { BsAndros as BahamasAndros } from './BsAndros.js';
export { BsAndros } from './BsAndros.js';
export { Bt as Bhutan } from './Bt.js';
export { Bt } from './Bt.js';
export { Bv as BouvetIsland } from './Bv.js';
export { Bv } from './Bv.js';
export { Bw as Botswana } from './Bw.js';
export { Bw } from './Bw.js';
export { By as Belarus } from './By.js';
export { By } from './By.js';
export { Bz as Belize } from './Bz.js';
export { Bz } from './Bz.js';
export { Ca as Canada } from './Ca.js';
export { Ca } from './Ca.js';
export { Cc as CocosIslands } from './Cc.js';
export { Cc } from './Cc.js';
export { Cd as DrCongo } from './Cd.js';
export { Cd } from './Cd.js';
export { Cf as CentralAfricanRepublic } from './Cf.js';
export { Cf } from './Cf.js';
export { Cg as RepublicOfTheCongo } from './Cg.js';
export { Cg } from './Cg.js';
export { Ch as Switzerland } from './Ch.js';
export { Ch } from './Ch.js';
export { Ci as CoteDIvoire } from './Ci.js';
export { Ci } from './Ci.js';
export { Ck as CookIslands } from './Ck.js';
export { Ck } from './Ck.js';
export { Cl as Chile } from './Cl.js';
export { Cl } from './Cl.js';
export { Cm as Cameroon } from './Cm.js';
export { Cm } from './Cm.js';
export { Cn as China } from './Cn.js';
export { Cn } from './Cn.js';
export { Co as Colombia } from './Co.js';
export { Co } from './Co.js';
export { Cr as CostaRica } from './Cr.js';
export { Cr } from './Cr.js';
export { Cu as Cuba } from './Cu.js';
export { Cu } from './Cu.js';
export { Cv as CapeVerde } from './Cv.js';
export { Cv } from './Cv.js';
export { Cw as Curacao } from './Cw.js';
export { Cw } from './Cw.js';
export { Cx as ChristmasIsland } from './Cx.js';
export { Cx } from './Cx.js';
export { Cy as Cyprus } from './Cy.js';
export { Cy } from './Cy.js';
export { Cz as Czechia } from './Cz.js';
export { Cz } from './Cz.js';
export { De as Germany } from './De.js';
export { De } from './De.js';
export { Dj as Djibouti } from './Dj.js';
export { Dj } from './Dj.js';
export { Dk as Denmark } from './Dk.js';
export { Dk } from './Dk.js';
export { Dm as Dominica } from './Dm.js';
export { Dm } from './Dm.js';
export { Do as DominicanRepublic } from './Do.js';
export { Do } from './Do.js';
export { Dz as Algeria } from './Dz.js';
export { Dz } from './Dz.js';
export { Ec as Ecuador } from './Ec.js';
export { Ec } from './Ec.js';
export { Ee as Estonia } from './Ee.js';
export { Ee } from './Ee.js';
export { Eg as Egypt } from './Eg.js';
export { Eg } from './Eg.js';
export { Eh as WesternSahara } from './Eh.js';
export { Eh } from './Eh.js';
export { England } from './England.js';
export { Er as Eritrea } from './Er.js';
export { Er } from './Er.js';
export { Es as Spain } from './Es.js';
export { Es } from './Es.js';
export { Et as Ethiopia } from './Et.js';
export { Et } from './Et.js';
export { Fi as Finland } from './Fi.js';
export { Fi } from './Fi.js';
export { Fj as Fiji } from './Fj.js';
export { Fj } from './Fj.js';
export { Fk as FalklandIslands } from './Fk.js';
export { Fk } from './Fk.js';
export { Fm as Micronesia } from './Fm.js';
export { Fm } from './Fm.js';
export { Fo as FaroeIslands } from './Fo.js';
export { Fo } from './Fo.js';
export { Fr as France } from './Fr.js';
export { Fr } from './Fr.js';
export { FrMainland as FranceMainland } from './FrMainland.js';
export { FrMainland } from './FrMainland.js';
export { Ga as Gabon } from './Ga.js';
export { Ga } from './Ga.js';
export { Gd as Grenada } from './Gd.js';
export { Gd } from './Gd.js';
export { Ge as Georgia } from './Ge.js';
export { Ge } from './Ge.js';
export { Gf as FrenchGuiana } from './Gf.js';
export { Gf } from './Gf.js';
export { Gg as Guernsey } from './Gg.js';
export { Gg } from './Gg.js';
export { Gh as Ghana } from './Gh.js';
export { Gh } from './Gh.js';
export { Gi as Gibraltar } from './Gi.js';
export { Gi } from './Gi.js';
export { Gl as Greenland } from './Gl.js';
export { Gl } from './Gl.js';
export { Gm as Gambia } from './Gm.js';
export { Gm } from './Gm.js';
export { Gn as Guinea } from './Gn.js';
export { Gn } from './Gn.js';
export { Gp as Guadeloupe } from './Gp.js';
export { Gp } from './Gp.js';
export { Gq as EquatorialGuinea } from './Gq.js';
export { Gq } from './Gq.js';
export { Gr as Greece } from './Gr.js';
export { Gr } from './Gr.js';
export { Gs as SouthGeorgiaAndTheSouthSandwichIslands } from './Gs.js';
export { Gs } from './Gs.js';
export { Gt as Guatemala } from './Gt.js';
export { Gt } from './Gt.js';
export { Gu as Guam } from './Gu.js';
export { Gu } from './Gu.js';
export { Gw as GuineaBissau } from './Gw.js';
export { Gw } from './Gw.js';
export { Gy as Guyana } from './Gy.js';
export { Gy } from './Gy.js';
export { Hk as HongKong } from './Hk.js';
export { Hk } from './Hk.js';
export { Hm as HeardIslandAndMcdonaldIslands } from './Hm.js';
export { Hm } from './Hm.js';
export { Hn as Honduras } from './Hn.js';
export { Hn } from './Hn.js';
export { Hr as Croatia } from './Hr.js';
export { Hr } from './Hr.js';
export { Ht as Haiti } from './Ht.js';
export { Ht } from './Ht.js';
export { Hu as Hungary } from './Hu.js';
export { Hu } from './Hu.js';
export { Id as Indonesia } from './Id.js';
export { Id } from './Id.js';
export { Ie as Ireland } from './Ie.js';
export { Ie } from './Ie.js';
export { Il as Israel } from './Il.js';
export { Il } from './Il.js';
export { Im as IsleOfMan } from './Im.js';
export { Im } from './Im.js';
export { In as India } from './In.js';
export { In } from './In.js';
export { Iq as Iraq } from './Iq.js';
export { Iq } from './Iq.js';
export { Ir as Iran } from './Ir.js';
export { Ir } from './Ir.js';
export { Is as Iceland } from './Is.js';
export { Is } from './Is.js';
export { It as Italy } from './It.js';
export { It } from './It.js';
export { Je as Jersey } from './Je.js';
export { Je } from './Je.js';
export { Jm as Jamaica } from './Jm.js';
export { Jm } from './Jm.js';
export { Jo as Jordan } from './Jo.js';
export { Jo } from './Jo.js';
export { Jp as Japan } from './Jp.js';
export { Jp } from './Jp.js';
export { Ke as Kenya } from './Ke.js';
export { Ke } from './Ke.js';
export { Kg as Kyrgyzstan } from './Kg.js';
export { Kg } from './Kg.js';
export { Kh as Cambodia } from './Kh.js';
export { Kh } from './Kh.js';
export { Ki as Kiribati } from './Ki.js';
export { Ki } from './Ki.js';
export { Km as Comoros } from './Km.js';
export { Km } from './Km.js';
export { Kn as SaintKittsAndNevis } from './Kn.js';
export { Kn } from './Kn.js';
export { Kp as NorthKorea } from './Kp.js';
export { Kp } from './Kp.js';
export { Kr as SouthKorea } from './Kr.js';
export { Kr } from './Kr.js';
export { Kw as Kuwait } from './Kw.js';
export { Kw } from './Kw.js';
export { Ky as CaymanIslands } from './Ky.js';
export { Ky } from './Ky.js';
export { Kz as Kazakhstan } from './Kz.js';
export { Kz } from './Kz.js';
export { La as Laos } from './La.js';
export { La } from './La.js';
export { Lb as Lebanon } from './Lb.js';
export { Lb } from './Lb.js';
export { Lc as SaintLucia } from './Lc.js';
export { Lc } from './Lc.js';
export { Li as Liechtenstein } from './Li.js';
export { Li } from './Li.js';
export { Lk as SriLanka } from './Lk.js';
export { Lk } from './Lk.js';
export { Lr as Liberia } from './Lr.js';
export { Lr } from './Lr.js';
export { Ls as Lesotho } from './Ls.js';
export { Ls } from './Ls.js';
export { Lt as Lithuania } from './Lt.js';
export { Lt } from './Lt.js';
export { Lu as Luxembourg } from './Lu.js';
export { Lu } from './Lu.js';
export { Lv as Latvia } from './Lv.js';
export { Lv } from './Lv.js';
export { Ly as Libya } from './Ly.js';
export { Ly } from './Ly.js';
export { Ma as Morocco } from './Ma.js';
export { Ma } from './Ma.js';
export { Mc as Monaco } from './Mc.js';
export { Mc } from './Mc.js';
export { Md as Moldova } from './Md.js';
export { Md } from './Md.js';
export { Me as Montenegro } from './Me.js';
export { Me } from './Me.js';
export { Mf as SaintMartin } from './Mf.js';
export { Mf } from './Mf.js';
export { Mg as Madagascar } from './Mg.js';
export { Mg } from './Mg.js';
export { Mh as MarshallIslands } from './Mh.js';
export { Mh } from './Mh.js';
export { Mk as NorthMacedonia } from './Mk.js';
export { Mk } from './Mk.js';
export { Ml as Mali } from './Ml.js';
export { Ml } from './Ml.js';
export { Mm as Myanmar } from './Mm.js';
export { Mm } from './Mm.js';
export { Mn as Mongolia } from './Mn.js';
export { Mn } from './Mn.js';
export { Mo as Macau } from './Mo.js';
export { Mo } from './Mo.js';
export { Mp as NorthernMarianaIslands } from './Mp.js';
export { Mp } from './Mp.js';
export { Mq as Martinique } from './Mq.js';
export { Mq } from './Mq.js';
export { Mr as Mauritania } from './Mr.js';
export { Mr } from './Mr.js';
export { Ms as Montserrat } from './Ms.js';
export { Ms } from './Ms.js';
export { Mt as Malta } from './Mt.js';
export { Mt } from './Mt.js';
export { Mu as Mauritius } from './Mu.js';
export { Mu } from './Mu.js';
export { Mv as Maldives } from './Mv.js';
export { Mv } from './Mv.js';
export { Mw as Malawi } from './Mw.js';
export { Mw } from './Mw.js';
export { Mx as Mexico } from './Mx.js';
export { Mx } from './Mx.js';
export { My as Malaysia } from './My.js';
export { My } from './My.js';
export { Mz as Mozambique } from './Mz.js';
export { Mz } from './Mz.js';
export { Na as Namibia } from './Na.js';
export { Na } from './Na.js';
export { Nc as NewCaledonia } from './Nc.js';
export { Nc } from './Nc.js';
export { Ne as Niger } from './Ne.js';
export { Ne } from './Ne.js';
export { Nf as NorfolkIsland } from './Nf.js';
export { Nf } from './Nf.js';
export { Ng as Nigeria } from './Ng.js';
export { Ng } from './Ng.js';
export { Ni as Nicaragua } from './Ni.js';
export { Ni } from './Ni.js';
export { Nl as Netherlands } from './Nl.js';
export { Nl } from './Nl.js';
export { No as Norway } from './No.js';
export { No } from './No.js';
export { NorthernIreland } from './NorthernIreland.js';
export { Np as Nepal } from './Np.js';
export { Np } from './Np.js';
export { Nr as Nauru } from './Nr.js';
export { Nr } from './Nr.js';
export { Nu as Niue } from './Nu.js';
export { Nu } from './Nu.js';
export { Nz as NewZealand } from './Nz.js';
export { Nz } from './Nz.js';
export { Om as Oman } from './Om.js';
export { Om } from './Om.js';
export { Pa as Panama } from './Pa.js';
export { Pa } from './Pa.js';
export { Pe as Peru } from './Pe.js';
export { Pe } from './Pe.js';
export { Pf as FrenchPolynesia } from './Pf.js';
export { Pf } from './Pf.js';
export { Pg as PapuaNewGuinea } from './Pg.js';
export { Pg } from './Pg.js';
export { Ph as Philippines } from './Ph.js';
export { Ph } from './Ph.js';
export { Pk as Pakistan } from './Pk.js';
export { Pk } from './Pk.js';
export { Pl as Poland } from './Pl.js';
export { Pl } from './Pl.js';
export { Pm as SaintPierreAndMiquelon } from './Pm.js';
export { Pm } from './Pm.js';
export { Pn as Pitcairn } from './Pn.js';
export { Pn } from './Pn.js';
export { Pr as PuertoRico } from './Pr.js';
export { Pr } from './Pr.js';
export { Ps as Palestine } from './Ps.js';
export { Ps } from './Ps.js';
export { Pt as Portugal } from './Pt.js';
export { Pt } from './Pt.js';
export { Pw as Palau } from './Pw.js';
export { Pw } from './Pw.js';
export { Py as Paraguay } from './Py.js';
export { Py } from './Py.js';
export { Qa as Qatar } from './Qa.js';
export { Qa } from './Qa.js';
export { Re as Reunion } from './Re.js';
export { Re } from './Re.js';
export { Ro as Romania } from './Ro.js';
export { Ro } from './Ro.js';
export { Rs as Serbia } from './Rs.js';
export { Rs } from './Rs.js';
export { Ru as Russia } from './Ru.js';
export { Ru } from './Ru.js';
export { Rw as Rwanda } from './Rw.js';
export { Rw } from './Rw.js';
export { Sa as SaudiArabia } from './Sa.js';
export { Sa } from './Sa.js';
export { Sb as SolomonIslands } from './Sb.js';
export { Sb } from './Sb.js';
export { Sc as Seychelles } from './Sc.js';
export { Sc } from './Sc.js';
export { Scotland } from './Scotland.js';
export { Sd as Sudan } from './Sd.js';
export { Sd } from './Sd.js';
export { Se as Sweden } from './Se.js';
export { Se } from './Se.js';
export { Sg as Singapore } from './Sg.js';
export { Sg } from './Sg.js';
export { Sh as SaintHelena } from './Sh.js';
export { Sh } from './Sh.js';
export { Si as Slovenia } from './Si.js';
export { Si } from './Si.js';
export { Sj as SvalbardAndJanMayen } from './Sj.js';
export { Sj } from './Sj.js';
export { Sk as Slovakia } from './Sk.js';
export { Sk } from './Sk.js';
export { Sl as SierraLeone } from './Sl.js';
export { Sl } from './Sl.js';
export { Sm as SanMarino } from './Sm.js';
export { Sm } from './Sm.js';
export { Sn as Senegal } from './Sn.js';
export { Sn } from './Sn.js';
export { So as Somalia } from './So.js';
export { So } from './So.js';
export { Sr as Suriname } from './Sr.js';
export { Sr } from './Sr.js';
export { Ss as SouthSudan } from './Ss.js';
export { Ss } from './Ss.js';
export { St as SaoTomeAndPrincipe } from './St.js';
export { St } from './St.js';
export { Sv as ElSalvador } from './Sv.js';
export { Sv } from './Sv.js';
export { Sx as SintMaarten } from './Sx.js';
export { Sx } from './Sx.js';
export { Sy as Syria } from './Sy.js';
export { Sy } from './Sy.js';
export { Sz as Eswatini } from './Sz.js';
export { Sz } from './Sz.js';
export { Tc as TurksAndCaicosIslands } from './Tc.js';
export { Tc } from './Tc.js';
export { Td as Chad } from './Td.js';
export { Td } from './Td.js';
export { Tf as FrenchSouthernTerritories } from './Tf.js';
export { Tf } from './Tf.js';
export { Tg as Togo } from './Tg.js';
export { Tg } from './Tg.js';
export { Th as Thailand } from './Th.js';
export { Th } from './Th.js';
export { Tj as Tajikistan } from './Tj.js';
export { Tj } from './Tj.js';
export { Tk as Tokelau } from './Tk.js';
export { Tk } from './Tk.js';
export { Tl as TimorLeste } from './Tl.js';
export { Tl } from './Tl.js';
export { Tm as Turkmenistan } from './Tm.js';
export { Tm } from './Tm.js';
export { Tn as Tunisia } from './Tn.js';
export { Tn } from './Tn.js';
export { To as Tonga } from './To.js';
export { To } from './To.js';
export { Tr as Turkiye } from './Tr.js';
export { Tr } from './Tr.js';
export { Tt as TrinidadAndTobago } from './Tt.js';
export { Tt } from './Tt.js';
export { Tv as Tuvalu } from './Tv.js';
export { Tv } from './Tv.js';
export { Tw as Taiwan } from './Tw.js';
export { Tw } from './Tw.js';
export { Tz as Tanzania } from './Tz.js';
export { Tz } from './Tz.js';
export { Ua as Ukraine } from './Ua.js';
export { Ua } from './Ua.js';
export { Ug as Uganda } from './Ug.js';
export { Ug } from './Ug.js';
export { Us as UnitedStates } from './Us.js';
export { Us } from './Us.js';
export { Uy as Uruguay } from './Uy.js';
export { Uy } from './Uy.js';
export { Uz as Uzbekistan } from './Uz.js';
export { Uz } from './Uz.js';
export { Va as VaticanCity } from './Va.js';
export { Va } from './Va.js';
export { Vc as SaintVincentAndTheGrenadines } from './Vc.js';
export { Vc } from './Vc.js';
export { Ve as Venezuela } from './Ve.js';
export { Ve } from './Ve.js';
export { Vg as VirginIslandsBritish } from './Vg.js';
export { Vg } from './Vg.js';
export { Vi as VirginIslandsUS } from './Vi.js';
export { Vi } from './Vi.js';
export { Vn as Vietnam } from './Vn.js';
export { Vn } from './Vn.js';
export { Vu as Vanuatu } from './Vu.js';
export { Vu } from './Vu.js';
export { Wales } from './Wales.js';
export { Wf as WallisAndFutuna } from './Wf.js';
export { Wf } from './Wf.js';
export { Ws as Samoa } from './Ws.js';
export { Ws } from './Ws.js';
export { Xk as Kosovo } from './Xk.js';
export { Xk } from './Xk.js';
export { Ye as Yemen } from './Ye.js';
export { Ye } from './Ye.js';
export { Yt as Mayotte } from './Yt.js';
export { Yt } from './Yt.js';
export { Za as SouthAfrica } from './Za.js';
export { Za } from './Za.js';
export { Zm as Zambia } from './Zm.js';
export { Zm } from './Zm.js';
export { Zw as Zimbabwe } from './Zw.js';
export { Zw } from './Zw.js';
