// SPDX-License-Identifier: GPL-3.0-only
// Commercial license available at https://geoicons.io
// AUTO-GENERATED by scripts/generate-keypair.js — do not edit by hand.
// ES256 (P-256) PUBLIC key. Verify-only; safe to ship in the package.
export const PUBLIC_KEY_JWK: JsonWebKey = {
  "kty": "EC",
  "crv": "P-256",
  "x": "HkHkadZP0cWxupxgwBjDkRF_f8m0ItEAzpBeoZy7In0",
  "y": "33QJaDakw8MGDu2GmHelyqXKYvP4DLRn0RJEXUHbUJM"
};
